[project]
name = "curiosity"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-ai-inference>=1.0.0b9",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
    "surrealdb>=1.0.6",
]
